{{- if .Values.tls.generate -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: '{{ .Values.tls.name }}-{{ .Values.suffix }}'
spec:
  commonName: '{{ .Values.host }}'
  secretName: '{{ .Values.tls.secretName }}'
  dnsNames:
    - '{{ .Values.host }}'
  issuerRef:
    kind: '{{ .Values.tls.issuer.kind }}'
    name: '{{ .Values.tls.issuer.name }}'
{{- end -}}
