apiVersion: v1
kind: ConfigMap
metadata:
  name: zakroma-backend-cm-{{ .Values.suffix }}
data:
  db_port: '{{ .Values.db.port }}'
  db_host: '{{ .Values.db.host }}'
  db_user: '{{ .Values.db.user }}'
  db_pass: '{{ .Values.db.pass }}'
  db_name: '{{ .Values.db.name }}'
  srv_host: '{{ .Values.host }}'
  srv_port: '{{ .Values.port }}'
